package com.advantech.model;
// Generated 2017/4/7 下午 02:26:06 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.apache.commons.lang3.ObjectUtils;

/**
 * LabelVariable generated by hbm2java
 */
@Entity
@Table(name = "LabelVariable",
        uniqueConstraints = @UniqueConstraint(columnNames = "name")
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id", scope = LabelVariable.class)
public class LabelVariable implements java.io.Serializable, Comparable<LabelVariable> {

    private int id;
    private LabelVariableGroup labelVariableGroup;
    private String name;

    @JsonIgnore
    private Set<Worktime> worktimesForLabelVariable11AffId = new HashSet<Worktime>(0);

    @JsonIgnore
    private Set<Worktime> worktimesForLabelVariable12AffId = new HashSet<Worktime>(0);

    @JsonIgnore
    private Set<LabelVariable> labelVariablesForChildId = new HashSet<LabelVariable>(0);

    @JsonIgnore
    private Set<LabelVariable> labelVariablesForParentId = new HashSet<LabelVariable>(0);

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "label_variable_group_id")
    public LabelVariableGroup getLabelVariableGroup() {
        return labelVariableGroup;
    }

    public void setLabelVariableGroup(LabelVariableGroup labelVariableGroup) {
        this.labelVariableGroup = labelVariableGroup;
    }

    @Column(name = "[name]", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "labelVariable11AffId")
    public Set<Worktime> getWorktimesForLabelVariable11AffId() {
        return worktimesForLabelVariable11AffId;
    }

    public void setWorktimesForLabelVariable11AffId(Set<Worktime> worktimesForLabelVariable11AffId) {
        this.worktimesForLabelVariable11AffId = worktimesForLabelVariable11AffId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "labelVariable12AffId")
    public Set<Worktime> getWorktimesForLabelVariable12AffId() {
        return worktimesForLabelVariable12AffId;
    }

    public void setWorktimesForLabelVariable12AffId(Set<Worktime> worktimesForLabelVariable12AffId) {
        this.worktimesForLabelVariable12AffId = worktimesForLabelVariable12AffId;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "LabelVariable_REF", joinColumns = {
        @JoinColumn(name = "label_parent_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "label_child_id", nullable = false, updatable = false)})
    public Set<LabelVariable> getLabelVariablesForChildId() {
        return labelVariablesForChildId;
    }

    public void setLabelVariablesForChildId(Set<LabelVariable> labelVariablesForChildId) {
        this.labelVariablesForChildId = labelVariablesForChildId;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "LabelVariable_REF", joinColumns = {
        @JoinColumn(name = "label_child_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "label_parent_id", nullable = false, updatable = false)})
    public Set<LabelVariable> getLabelVariablesForParentId() {
        return labelVariablesForParentId;
    }

    public void setLabelVariablesForParentId(Set<LabelVariable> labelVariablesForParentId) {
        this.labelVariablesForParentId = labelVariablesForParentId;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LabelVariable other = (LabelVariable) obj;
        if (Objects.equals(this.id, other.id)) {
            return true;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }

    @Override
    public int compareTo(LabelVariable o) {
        return ObjectUtils.compare(this.id, o.getId());
    }

}
