//Js檔用來給予下拉式表單使用(unit可編輯欄位需要區隔，記錄在db之中)
var worktimeCol = [
    {name: "id", editable: false},
    {name: "modelName"},
    {name: "type.id"},
    {name: "productionWt", editable: false},
    {name: "totalModule", editable: false},
    {name: "setupTime", editable: false},
    {name: "cleanPanel", editable: false},
    {name: "preAssyModuleQty"},
    {name: "assy", editable: false},
    {name: "t1", editable: false},
    {name: "t2", editable: false},
    {name: "t3", editable: false},
    {name: "t4", editable: false},
    {name: "packing", editable: false},
    {name: "upBiRi", editable: false},
    {name: "downBiRi", editable: false},
    {name: "upRi", editable: false},
    {name: "downRi", editable: false},
    {name: "biCost", editable: false},
    {name: "vibration", editable: false},
    {name: "hiPotLeakage", editable: false},
    {name: "coldBoot", editable: false},
    {name: "warmBoot", editable: false},
    {name: "assyToT1", editable: false},
    {name: "t2ToPacking", editable: false},
    {name: "floor.id", editable: false},
    {name: "pending.id"},
    {name: "pendingTime"},
    {name: "burnIn"},
    {name: "biSampling"},
    {name: "biTime"},
    {name: "biTemperature"},
    {name: "biPower", editable: false},
    {name: "userBySpeOwnerId.id"},
    {name: "userByEeOwnerId.id"},
    {name: "userByQcOwnerId.id"},
    {name: "userByMpmOwnerId.id"},
    {name: "assyPackingSop", editable: false},
    {name: "testSop", editable: false},
    {name: "keypartA"},
    {name: "keypartB"},
    {name: "preAssy.id"},
    {name: "flowByBabFlowId.id"},
    {name: "flowByTestFlowId.id"},
    {name: "flowByPackingFlowId.id"},
    {name: "partLink"},
    {name: "ce"},
    {name: "ul"},
    {name: "rohs"},
    {name: "weee"},
    {name: "madeInTaiwan"},
    {name: "fcc"},
    {name: "eac"},
    {name: "kc"},
    {name: "nsInOneCollectionBox"},
    {name: "partNoAttributeMaintain"},
    {name: "acwVoltage"},
    {name: "dcwVoltage"},
    {name: "irVoltage"},
    {name: "testProfile"},
    {name: "lltValue"},
    {name: "gndValue"},
    {name: "weight"},
    {name: "weightAff"},
    {name: "tolerance"},
    {name: "assyStation", editable: false},
    {name: "packingStation", editable: false},
    {name: "assyLeadTime", editable: false},
    {name: "assyKanbanTime", editable: false},
    {name: "packingLeadTime"},
    {name: "packingPalletTime"},
    {name: "packingKanbanTime", editable: false},
    {name: "cleanPanelAndAssembly", editable: false},
    {name: "modifiedDate", editable: false},
    {name: "bwFields.0.assyAvg", editable: false},
    {name: "bwFields.0.packingAvg", editable: false},
    {name: "businessGroup.id"},
    {name: "workCenter", editable: false},
    {name: "burnInQuantity"},
    {name: "sapWt", editable: false},
    {name: "macTotalQty"},
    {name: "macPrintedQty"},
    {name: "twm2Flag"},
    {name: "hrcValues"},
    {name: "t1StatusQty"},
    {name: "t1ItemsQty"},
    {name: "t2StatusQty"},
    {name: "t2ItemsQty"},
    {name: "machineWorktime", editable: false},
    {name: "cobots"},
    {name: "cobotManualWt"},
    {name: "labelMac"},
    {name: "macPrintedLocation"},
    {name: "macPrintedFrom"},
    {name: "etlVariable1"},
    {name: "etlVariable2"},
    {name: "etlVariable3"},
    {name: "etlVariable1Aff"},
    {name: "etlVariable2Aff"},
    {name: "etlVariable3Aff"},
    {name: "labelYN"},
    {name: "ssnOnTag"},
    {name: "labelOuterId.id"},
    {name: "labelCartonId.id"},
    {name: "labelOuterCustom"},
    {name: "labelCartonCustom"},
    {name: "labelBigCarton"},
    {name: "label2D"},
    {name: "labelCustomerSn"},
    {name: "labelPn"},
    {name: "labelNmodelA"},
    {name: "labelNmodelB"},
    {name: "labelAssyInput"},
    {name: "labelVariable1"},
    {name: "labelVariable2"},
    {name: "labelVariable3"},
    {name: "labelVariable4"},
    {name: "labelVariable5"},
    {name: "labelVariable6"},
    {name: "labelVariable7"},
    {name: "labelVariable8"},
    {name: "labelVariable9"},
    {name: "labelVariable10"},
    {name: "labelVariable11"},
    {name: "labelVariable12"},
    {name: "labelVariable1Aff"},
    {name: "labelVariable2Aff"},
    {name: "labelVariable3Aff"},
    {name: "labelVariable4Aff"},
    {name: "labelVariable5Aff"},
    {name: "labelVariable6Aff"},
    {name: "labelVariable7Aff"},
    {name: "labelVariable8Aff"},
    {name: "labelVariable9Aff"},
    {name: "labelVariable10Aff"},
    {name: "labelVariable11AffId.id"},
    {name: "labelVariable12AffId.id"},
    {name: "labelPacking1"},
    {name: "labelPacking2"},
    {name: "labelPacking3"},
    {name: "labelPacking4"},
    {name: "labelPacking5"},
    {name: "labelPacking6"},
    {name: "labelPacking7"},
    {name: "labelPacking8"},
    {name: "labelPacking9"},
    {name: "labelPacking10"},
    {name: "keypartValueLabel"},
    {name: "keypartBlockFlag"},
    {name: "shippingPallet"},
    {name: "assyCheckSsn"},
    {name: "ssnPrefix"},
    {name: "ssnLength"}
];

//不受show / hide 影響
var do_not_change_columns = [
    "id", "rowId", "modifiedDate", "bwFields.0.assyAvg", "bwFields.0.packingAvg", "createDate", "floor.id",
    "assyStation", "packingStation", "assyKanbanTime", "packingKanbanTime", "biPower"
//    "machineWorktime", "productionWt", "setupTime", "cleanPanel", "totalModule", "assy", "t1", "t2", "t3", "t4", "packing", "upBiRi", "downBiRi", "vibration", "hiPotLeakage", "coldBoot", "warmBoot", "assyToT1", "t2ToPacking", "packingLeadTime", "packingPalletTime", "cleanPanelAndAssembly", "sapWt",
//    "workCenter", "biCost", "assyLeadTime"
];

//指定的column要有checkbox，且新增時候預設1
var formulaColumn = [
    "productionWt",
    "setupTime",
    "assyToT1",
    "t2ToPacking",
//    "assyStation",
//    "packingStation",
//    "assyKanbanTime",
//    "packingKanbanTime",
    "cleanPanelAndAssembly",
    "machineWorktime",
    "cobotManualWt"
];

//group column for modal
var group = [
    {
        Type0: ['tr_modelName', 'tr_type.id', 'tr_businessGroup.id', 'tr_userBySpeOwnerId.id', 'tr_userByEeOwnerId.id', 'tr_userByQcOwnerId.id', 'tr_floor.id',
            'tr_userByMpmOwnerId.id', 'tr_keypartA', 'tr_keypartB', 'tr_partLink', 'tr_ce', 'tr_ul', 'tr_rohs', 'tr_weee', 'tr_madeInTaiwan',
            'tr_fcc', 'tr_eac', 'tr_kc', 'tr_nsInOneCollectionBox', 'tr_partNoAttributeMaintain', 'tr_weight', 'tr_weightAff', 'tr_tolerance', 'tr_preAssyModuleQty',
            'tr_burnInQuantity', 'tr_createDate', 'tr_modifiedDate', 'tr_twm2Flag', 'tr_cobots',
            'tr_keypartValueLabel', 'tr_keypartBlockFlag', 'tr_shippingPallet']
    },
    {
        Type1: ['tr_preAssy.id', 'tr_flowByBabFlowId.id', 'tr_flowByTestFlowId.id', 'tr_flowByPackingFlowId.id',
            'tr_burnIn', 'tr_biTime', 'tr_biTemperature', 'tr_biCost', 'tr_pending.id', 'tr_pendingTime', 'tr_biSampling',
            'tr_workCenter', 'tr_assyLeadTime', 'tr_packingLeadTime', 'tr_packingPalletTime']
    },
    {
        Type2: ['tr_labelYN', 'tr_ssnOnTag', 'tr_labelOuterId.id', 'tr_labelOuterCustom', 'tr_labelCartonId.id', 'tr_labelCartonCustom', 'tr_labelBigCarton', 'tr_label2D', 'tr_labelCustomerSn', 'tr_labelPn', 'tr_labelNmodelA', 'tr_labelNmodelB', , 'tr_labelAssyInput',
            'tr_labelVariable1', 'tr_labelVariable2', 'tr_labelVariable3', 'tr_labelVariable4', 'tr_labelVariable5', 'tr_labelVariable6', 'tr_labelVariable7', 'tr_labelVariable8', 'tr_labelVariable9', 'tr_labelVariable10', 'tr_labelVariable11', 'tr_labelVariable12',
            'tr_labelVariable1Aff', 'tr_labelVariable2Aff', 'tr_labelVariable3Aff', 'tr_labelVariable4Aff', 'tr_labelVariable5Aff', 'tr_labelVariable6Aff', 'tr_labelVariable7Aff', 'tr_labelVariable8Aff', 'tr_labelVariable9Aff', 'tr_labelVariable10Aff', 'tr_labelVariable11AffId.id', 'tr_labelVariable12AffId.id',
            'tr_labelPacking1', 'tr_labelPacking2', 'tr_labelPacking3', 'tr_labelPacking4', 'tr_labelPacking5', 'tr_labelPacking6', 'tr_labelPacking7', 'tr_labelPacking8', 'tr_labelPacking9', 'tr_labelPacking10',
            'tr_assyCheckSsn', 'tr_ssnPrefix', 'tr_ssnLength']
    },
    {
        Type3: ['tr_macTotalQty', 'tr_macPrintedQty', 'tr_labelMac', 'tr_macPrintedLocation', 'tr_macPrintedFrom', 'tr_etlVariable1', 'tr_etlVariable2', 'tr_etlVariable3', 'tr_etlVariable1Aff', 'tr_etlVariable2Aff', 'tr_etlVariable3Aff']
    },
    {
        Type4: ['tr_testProfile', 'tr_acwVoltage', 'tr_dcwVoltage', 'tr_irVoltage', 'tr_gndValue', 'tr_lltValue']
    },
    {
        Type5: ['tr_t1StatusQty', 'tr_t1ItemsQty', 'tr_t2StatusQty', 'tr_t2ItemsQty']
    }
];

var getClassification_Type = function (cssid) {
    for (var count = 0; count < group.length; count++) {
        if (group[count]['Type' + count].indexOf(cssid) !== -1) {
            return 'Type' + count;
        }
    }
};